permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

# 作者信息
author: 
  name: xinmeng
  email: mengxin.city@gmail.com
  link: emx2.co.uk
  weibo: http://weibo.com/ 
  github: http://github.com/xinmeng1

# 站点信息
title: Xin Meng's Blog
description: Xin Meng's Blog
url: emx2.co.uk
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: http://yansu-uploads.stor.sinaapp.com/imgs/gavatar.png
favicon: http://yansu-uploads.stor.sinaapp.com/imgs/favicon.ico

# google analytics 设置
ga:
  id: UA-54767140-1
  url: emx2.co.uk

# disqus 设置
disqus:
  shortname: mengxin

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Python

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
